### PR TITLE
Address the situation where the `ember-cli-build.js` could not be edi…

### LINKED ISSUE #279: Default blueprint fails for unexpected `ember-cli-build.js` structure
I get this:
```
07:48 $ ember generate ember-bootstrap
installing ember-bootstrap
Installing for Bootstrap 3 using preprocessor sass
  uninstall bower package bootstrap
  uninstall package bootstrap
  install package bootstrap-sass
NPM: Uninstalled bootstrap

NPM: Installed bootstrap-sass@^3.3.7
Added import statement to app/styles/app.scss
Added ember-bootstrap configuration to ember-cli-build.js
Cannot read property 'properties' of undefined
TypeError: Cannot read property 'properties' of undefined
    at EmberBuildConfigEditor.findOrAddConfigKey (/Users/rstudner/projects/expel-ember/node_modules/ember-cli-build-config-editor/lib/build-config-editor.js:52:36)
    at EmberBuildConfigEditor.edit (/Users/rstudner/projects/expel-ember/node_modules/ember-cli-build-config-editor/lib/build-config-editor.js:95:40)
    at Class.addBuildConfiguration (/Users/rstudner/projects/expel-ember/node_modules/ember-bootstrap/blueprints/ember-bootstrap/index.js:193:28)
    at adjustBootstrapDependencies.then.then.then (/Users/rstudner/projects/expel-ember/node_modules/ember-bootstrap/blueprints/ember-bootstrap/index.js:73:24)
    at tryCatch (/Users/rstudner/projects/expel-ember/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/rstudner/projects/expel-ember/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/rstudner/projects/expel-ember/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/rstudner/projects/expel-ember/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### PR DESCRIPTION
**Pull request by srvance**
…ted with an instructional message to manually edit the configuration.

Fixes #279.

### CODE REVIEW

File: blueprints/ember-bootstrap/index.js [hunk 1]
```diff
@@ -186,14 +186,21 @@ module.exports = {
...
-      let build = new BuildConfigEditor(source);
-      let newBuild = build.edit('ember-bootstrap', settings);
-      fs.writeFileSync(file, newBuild.code());
-    } else {
+    if (!fs.existsSync(file)) {
       this.ui.writeLine(chalk.red(`Could not find ${file} to modify.`));
+      return;
+    }
+
+    this.ui.writeLine(chalk.green(`Added ember-bootstrap configuration to ${file}`));
```
Comment (simonihmig) [inline blueprints/ember-bootstrap/index.js]: Shouldn't this be rather the last line of the `try` block, when we know that it was successful?

Comment (srvance) [inline blueprints/ember-bootstrap/index.js]: Done. All the others are optimistic, but this makes sense to be more pessimistic under the circumstances.

Comment (srvance) [inline blueprints/ember-bootstrap/index.js]: We could change the messages to "adding" rather than "added" if we want to communicate what's being attempted.

Comment (simonihmig) [inline blueprints/ember-bootstrap/index.js]: Yes, that would be ok as well

Comment (srvance) [inline blueprints/ember-bootstrap/index.js]: Do you have a preference?

Comment (simonihmig) [inline blueprints/ember-bootstrap/index.js]: I think it is good how it is now!

**Comment by simonihmig** [comment]
Thanks! 👍

**Comment by rstudner** [comment]
Wanted to say I tested this by pointing at ember-bootstrap#master.  I received the warning and the output was clear to follow and everything worked following the steps.
