### PR TITLE
Fix Dropdown with a block=true toggle button

### LINKED ISSUE #244: Change dropdown class "btn-group" to "dropdown"
I use Dropdown component,  with button block=true.

### PR DESCRIPTION
**Pull request by simonihmig**
Fixes #244

### CODE REVIEW

File: addon/components/base/bs-dropdown.js [hunk 1]
```diff
@@ -154,7 +154,7 @@ export default Ember.Component.extend({
    * @private
    */
   containerClass: computed('toggle.tagName', 'direction', function() {
-    if (this.get('toggle.tagName') === 'button') {
+    if (this.get('toggle.tagName') === 'button' && this.get('toggle.block') !== true) {
```
Comment (srvance) [inline addon/components/base/bs-dropdown.js]: Either `!this.get('toggle.block')` or `this.get('toggle.block') === false`? The former is more permissive and would require the property to be initialized reliably.
