### PR TITLE
Fix keyboard control of Dropdowns rendered in a wormhole

### LINKED ISSUE #936: support focus trapping when bs-dropdown is rendered in wormhole
Thank you for building this component and for your hard work on making these components accessible.

I've noticed something regarding focus trapping of `<BsDropdown>` when the menu has `renderInPlace={{false}}`, focus trapping is not applied to the menu. I've added it manually but it would be great to have this fixed.

In case I am missing something, here is my component markup without the fix:

 `"ember-bootstrap": "^3.1.0"`
```
<BsDropdown @class="hidden-print" @onHide={{action (mut open) false}} @onShow={{action (mut open) true}} as |dd|>
  <dd.button @class="btn-no-border"
    @title={{if open (t "explore.interactionsDropdown.collapse") (t "explore.interactionsDropdown.expand")}}
    onclick={{action "onDropdownToggle" dd.toggleDropdown}}>
  </dd.button>
  <dd.menu @class="{{styleNamespace}}-explore-card-popover-menu" @align="right" @renderInPlace={{false}} as |ddm|>
      <ddm.item>
        <button class="{{styleNamespace}}-btn-flex btn-link" onclick={{@doSomething}}>
          <div class="{{styleNamespace}}-svg-wrapper">
            <BuIcon @fileName="icon-nav" @className="{{styleNamespace}}-icon-ellipsis" />
          </div>
          some text
        </button>
      </ddm.item>
  </dd.menu>

</BsDropdown>
```
I fixed it by using `ember-focus-trapper` and wrapping `<FocusTrapper>` around the `<ddm.item>` element.

Thanks again

### PR DESCRIPTION
**Pull request by simonihmig**
Fixes #936

### CODE REVIEW

File: addon/components/base/bs-dropdown.js [hunk 1]
```diff
@@ -293,6 +293,7 @@ export default class Dropdown extends Component {
   openDropdown() {
     this.set('isOpen', true);
     this.get('onShow')();
+    // schedule('afterRender', () => this.menuElement.focus());
```
Comment (jelhan) [inline addon/components/base/bs-dropdown.js]: I guess just a left over from developing this one?

```suggestion
```

Comment (simonihmig) [reply addon/components/base/bs-dropdown.js]: oh, yes :)

**Comment by seemajune** [comment]
💯
